name: tahiti
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
  flutter_svg: ^0.6.3
  audio_recorder:
    git:
      url: git://github.com/ZaraclaJ/audio_recorder.git
      ref: 7957e5adbeaa863ee17c9f5c29d4b5538e5a7cb3
  audioplayers: ^0.7.8 
  path_provider: ^0.4.1
  scoped_model: ^0.3.0
  image_picker: ^0.4.10
  video_player: ^0.7.2
  uuid: ^1.0.3
  tuple: ^1.0.2
  nima: ^1.0.1
  json_annotation: ^2.0.0
  shared_preferences: ^0.4.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.1.1
  json_serializable: ^2.0.0
# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: org.chimple.tahiti
    pluginClass: TahitiPlugin
  assets:
    - assets/camera/camera1.png
    - assets/camera/gallery.png 
    - assets/camera/video.png
    - assets/menu/
    - assets/menu/svg/
    - assets/drawing/size1.png
    - assets/drawing/size2.png
    - assets/drawing/size3.png
    - assets/drawing/size4.png
    - assets/drawing/size5.png
    - assets/menu/stickers.png
    - assets/mic/mic.png
    - assets/mic/play.png
    - assets/mic/stop.png
    - assets/filter_icon.jpg
    - assets/roller_image/sample1.jpg
    - assets/roller_image/sample2.jpg
    - assets/roller_image/sample3.jpg
    - assets/roller_image/sample4.jpg
    - assets/roller_image/sample5.jpg
    - assets/filter_image/filterImage1.png
    - assets/filter_image/filterImage2.png
    - assets/filter_image/filterImage3.png
    - assets/filter_image/filterImage4.png
    - assets/filter_image/filterImage5.png
    - assets/filter_image/filterImage6.png
    - assets/svgimage/bodyparts/
    - assets/svgimage/fooditem/
    - assets/svgimage/clothes/
    - assets/svgimage/fruits/
    - assets/svgimage/vehicles/
    - assets/svgimage/shape/
    - assets/svgimage/number/
    - assets/svgimage/emotion/
    - assets/svgimage/furniture/
    - assets/svgimage/grains/
    - assets/svgimage/alphabet/
    - assets/svgimage/animals/
    - assets/svgimage/electronics/
    - assets/svgimage/homeutility/
    - assets/svgimage/housebuilding/
    - assets/svgimage/occupation_men/
    - assets/svgimage/occupation_women/
    - assets/svgimage/stationary/
    - assets/svgimage/tools/
    - assets/svgimage/zodiac/
    - assets/nima_animation/
  fonts:
    - family: Bungee
      fonts:
        - asset: assets/fonts/Bungee-Regular.ttf
    - family: Chela one
      fonts:
        - asset: assets/fonts/ChelaOne-Regular.ttf
    - family: Gloria Hallelujah
      fonts:
        - asset: assets/fonts/GloriaHallelujah.ttf
    - family: Great vibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf
    - family: Homemade apple
      fonts:
        - asset: assets/fonts/HomemadeApple-Regular.ttf
    - family: Indie Flower
      fonts:
        - asset: assets/fonts/IndieFlower.ttf
    - family: Kirang Haerang
      fonts:
        - asset: assets/fonts/KirangHaerang-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Patrick Hand
      fonts:
        - asset: assets/fonts/PatrickHand-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Rock salt
      fonts:
        - asset: assets/fonts/RockSalt-Regular.ttf
    - family: Shadows into light
      fonts:
        - asset: assets/fonts/ShadowsIntoLight.ttf
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.

environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"